const baseExercises = [
['oberer Rücken','abgespreiztes Kurzhantelziehen','Kurzhantel'],['oberer Rücken','Weit-Arm-Bandziehen / Face Pulls','Band'],['oberer Rücken','Band weit-Arm-ziehen','Band'],['Rücken','Klimmzüge','Körpergewicht'],['mittlerer Rücken','Band-Rudern','Band'],['Brust','Kurzhantelbankdrücken','Kurzhantel + Bank'],['obere Brust','Kurzhantel-Schrägbankdrücken','Kurzhantel + Bank'],['untere Brust','Kurzhantel-Schrägbodendrücken','Kurzhantel'],['Bauch','Crunches + Seitcrunches','Körpergewicht'],['Bauch','Crunches am Band + Hüftrotation','Band'],['Bauch','Bein hochziehen + Hüftrotation','Körpergewicht'],['Schultern','Kurzhantel-Schulterdrücken','Kurzhantel'],['seitliche Schultern','Kurzhantel-Seitheben (2 s)','Kurzhantel'],['seitliche Schultern','Band-Reverse-Ziehen','Band'],['hintere Schultern','Kurzhantel Reverse Butterfly','Kurzhantel'],['vordere Schulter','Kurzhantel Frontheben','Kurzhantel'],['Schultern','Handstand-Push-ups','Körpergewicht'],['Beine','Kurzhantel-Kreuzheben','Kurzhantel'],['Beine','Bulgarian Split Squats','Kurzhantel + Bank'],['Waden','Wadenheben an der Bank','Kurzhantel + Bank'],['Oberschenkel','Bank-Drücken (Keller)','Bank'],['Po','Über-Kreuz-Gehen','Band'],['Po','Hip Thrusts einbeinig','Bank'],['Po','Hanteleseltritte','Kurzhantel'],['Bizeps','Kurzhantel-Hammercurls','Kurzhantel'],['Bizeps','Bizepscurls auf Schrägbank','Kurzhantel + Bank'],['Unterarmbeuger','Kurzhantel Curls','Kurzhantel'],['Unterarmbeuger','Band Curls','Band'],['Unterarmstrecker','Kurzhantel Reverse Curls','Kurzhantel'],['Unterarmstrecker','Band Reverse Curls','Band'],['Unterarm','Handquetscher','Handtrainer'],['Trizeps','Kurzhantel über Kopf','Kurzhantel'],['Brust','Liegestütze','Körpergewicht']
].map((x,i)=>({id:'e'+i,group:x[0],name:x[1],equipment:x[2],target:'3 × 8–12',load:'',active:true,history:[]}));
const todayNames = new Set(['abgespreiztes Kurzhantelziehen','Band weit-Arm-ziehen','Kurzhantel-Schrägbodendrücken','Crunches + Seitcrunches','Kurzhantel-Seitheben (2 s)','Kurzhantel Frontheben','Kurzhantel-Kreuzheben','Wadenheben an der Bank','Über-Kreuz-Gehen','Hanteleseltritte','Kurzhantel Curls','Band Curls','Kurzhantel Reverse Curls','Band Reverse Curls','Kurzhantel über Kopf']);
const skills = [
{name:'Pistol Squat',icon:'🦵',family:'Beine',boss:'Der Einbeinige',steps:['15 saubere Squats','Split Squat 10/Seite','Box Pistol','Pistol mit Unterstützung','Negativ-Pistol','Freier Pistol Squat'],metric:'Wdh.'},
{name:'L-Sit',icon:'🪑',family:'Core',boss:'Der Kompressor',steps:['Stütz halten','Knie anheben','Tuck Sit','Ein Bein strecken','Beide Beine teilweise','Voller L-Sit'],metric:'Sek.'},
{name:'Handstand',icon:'🤸',family:'Balance',boss:'Die verkehrte Welt',steps:['Wrist Prep + Pike Hold','Wall Walk','Bauch-zur-Wand-Hold','Kick-up an Wand','Freier Hold 5 s','Freier Hold 30 s'],metric:'Sek.'},
{name:'Handstand Push-up',icon:'⬆️',family:'Push',boss:'Der Turm',steps:['Pike Push-up','Erhöhte Pike Push-up','Negativer Wall HSPU','Wall HSPU','Deficit Wall HSPU','Freier HSPU'],metric:'Wdh.'},
{name:'Muscle-up',icon:'🚀',family:'Pull',boss:'Der Türsteher',steps:['8 Pull-ups','Chest-to-Bar','Explosive Pull-ups','Straight-Bar-Dip','Band Muscle-up','Strict Muscle-up'],metric:'Wdh.'},
{name:'Front Lever',icon:'🦇',family:'Pull',boss:'Der Abgrund',steps:['Active Hang','Tuck Lever','Advanced Tuck','Single Leg','Straddle','Full Front Lever'],metric:'Sek.'},
{name:'Back Lever',icon:'🌒',family:'Pull',boss:'Die Rückseite',steps:['German Hang','Skin the Cat','Tuck Back Lever','Advanced Tuck','Straddle','Full Back Lever'],metric:'Sek.'},
{name:'Planche',icon:'🛸',family:'Push',boss:'Der Tempel',steps:['Planche Lean','Frog Stand','Tuck Planche','Advanced Tuck','Straddle Planche','Full Planche'],metric:'Sek.'},
{name:'Human Flag',icon:'🚩',family:'Side/Core',boss:'Der Fahnenträger',steps:['Side Plank','Vertical Flag Hold','Tuck Flag','One-Leg Flag','Straddle Flag','Full Human Flag'],metric:'Sek.'},
{name:'Dragon Flag',icon:'🐉',family:'Core',boss:'Der Drache',steps:['Hollow Hold','Leg Raises','Negative Dragon Flag','Tuck Dragon Flag','One-Leg Dragon','Full Dragon Flag'],metric:'Wdh.'},
{name:'One-Arm Pull-up',icon:'🦍',family:'Pull',boss:'Der Titan',steps:['10 Pull-ups','Archer Pull-up','Typewriter Pull-up','Assisted One-Arm','Negative One-Arm','One-Arm Pull-up'],metric:'Wdh.'},
{name:'V-Sit',icon:'✌️',family:'Core',boss:'Der Winkel',steps:['Tuck Sit','L-Sit 15 s','L-Sit 30 s','High L-Sit','Tuck V-Sit','V-Sit'],metric:'Sek.'},
{name:'Press to Handstand',icon:'🔺',family:'Balance',boss:'Der Aufstieg',steps:['Pike Compression','Frog Stand','Straddle Compression','Box Press Drill','Negative Press','Press Handstand'],metric:'Wdh.'},
{name:'90° Hold',icon:'📐',family:'Push',boss:'Der rechte Winkel',steps:['Push-up Hold','Pseudo Planche Push-up','Bent-Arm Stand','Negative 90°','Assisted 90°','90° Hold'],metric:'Sek.'},
{name:'Shrimp Squat',icon:'🦐',family:'Beine',boss:'Die Garnele',steps:['Split Squat','Reverse Lunge','Assisted Shrimp','Partial Shrimp','Full Shrimp','Weighted Shrimp'],metric:'Wdh.'},
{name:'Dragon Squat',icon:'🐲',family:'Beine',boss:'Der Knoten',steps:['Cossack Squat','Curtsy Lunge','Assisted Dragon','Partial Dragon','Full Dragon','Weighted Dragon'],metric:'Wdh.'},
{name:'Handstand Walk',icon:'🚶',family:'Balance',boss:'Der Spaziergang',steps:['Wall Handstand 30 s','Shoulder Taps','Wall Walk-offs','2 freie Schritte','5 freie Schritte','10 m Handstand Walk'],metric:'Meter'},
{name:'One-Arm Handstand',icon:'☝️',family:'Balance',boss:'Der Monolith',steps:['Handstand 45 s','Weight Shifts','Finger-Assisted Hold','One-Hand Wall Hold','2 s One-Arm','10 s One-Arm'],metric:'Sek.'}
].map((s,i)=>({...s,id:'s'+i}));

const skillPlans = {
'L-Sit':{source:'https://www.youtube.com/results?search_query=L-Sit+progression+calisthenics+tutorial',visual:skills.find(x=>x.name==='L-Sit')?.icon||'🎯',intro:'Stützkraft, Kompression und Core-Spannung.',gate:'3 × 20 s sauber',drills:[{name:'Stütz halten auf Bank',dose:'3 × 20 s',cue:'Schultern aktiv nach unten drücken, Ellbogen gestreckt.',error:'Einsinken in die Schultern; gebeugte Arme.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Stütz halten auf Bank calisthenics tutorial')},{name:'Sitzende Kniehebe-Kompression',dose:'3 × 12',cue:'Aufrecht sitzen und Knie aktiv zur Brust ziehen.',error:'Zurücklehnen und Schwung holen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Sitzende Kniehebe-Kompression calisthenics tutorial')},{name:'Tuck L-Sit',dose:'3 × 15 s',cue:'Knie zur Brust, Hüfte zwischen den Händen.',error:'Füße absetzen; Schultern hochziehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Tuck L-Sit calisthenics tutorial')}]},
'Handstand':{source:'https://www.youtube.com/results?search_query=handstand+progression+beginner+calisthenics+tutorial',visual:skills.find(x=>x.name==='Handstand')?.icon||'🎯',intro:'Handgelenke, Schulterlinie, Wandkontrolle und Balance.',gate:'3 × 30 s Bauch-zur-Wand',drills:[{name:'Handgelenk-Prep',dose:'3 Min',cue:'Finger spreizen, Belastung langsam steigern.',error:'Kalt direkt in maximale Belastung.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Handgelenk-Prep calisthenics tutorial')},{name:'Bauch-zur-Wand-Handstand',dose:'3 × 30 s',cue:'Rippen einziehen, Po anspannen, aktiv aus Schultern drücken.',error:'Hohlkreuz; Kopf stark herausstrecken.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Bauch-zur-Wand-Handstand calisthenics tutorial')},{name:'Wall Floats',dose:'5 × 10 s',cue:'Füße kurz lösen und über Finger balancieren.',error:'Von der Wand abspringen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Wall Floats calisthenics tutorial')}]},
'Pistol Squat':{source:'https://www.youtube.com/results?search_query=pistol+squat+progression+beginner+tutorial',visual:skills.find(x=>x.name==='Pistol Squat')?.icon||'🎯',intro:'Einbeinige Kraft, Balance und Sprunggelenksbeweglichkeit.',gate:'3 × 8 Box Pistols je Seite',drills:[{name:'Split Squat',dose:'3 × 10 je Seite',cue:'Vorderes Knie kontrolliert, voller Fuß belastet.',error:'Knie kollabiert nach innen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Split Squat calisthenics tutorial')},{name:'Box Pistol',dose:'3 × 8 je Seite',cue:'Langsam auf Bank setzen, ohne fallen zu lassen.',error:'Auf die Bank plumpsen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Box Pistol calisthenics tutorial')},{name:'Assisted Pistol',dose:'3 × 6 je Seite',cue:'Nur so viel Hilfe wie nötig.',error:'Mit den Armen hochziehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Assisted Pistol calisthenics tutorial')}]},
'Handstand Push-up':{source:'https://www.youtube.com/results?search_query=handstand+push+up+progression+calisthenics',visual:skills.find(x=>x.name==='Handstand Push-up')?.icon||'🎯',intro:'Vertikale Druckkraft plus sichere Handstandposition.',gate:'3 × 8 erhöhte Pike Push-ups',drills:[{name:'Pike Push-up',dose:'3 × 10',cue:'Kopf vor den Händen absenken, Hüfte hoch.',error:'Wie normalen Push-up ausführen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Pike Push-up calisthenics tutorial')},{name:'Erhöhte Pike Push-up',dose:'3 × 8',cue:'Füße erhöht, kontrollierte Tiefe.',error:'Hohlkreuz und halbe Wiederholungen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Erhöhte Pike Push-up calisthenics tutorial')},{name:'Negative Wall HSPU',dose:'4 × 3',cue:'3–5 Sekunden kontrolliert ablassen.',error:'Nach unten fallen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Negative Wall HSPU calisthenics tutorial')}]},
'Muscle-up':{source:'https://www.youtube.com/results?search_query=muscle+up+progression+FitnessFAQs+tutorial',visual:skills.find(x=>x.name==='Muscle-up')?.icon||'🎯',intro:'Hoher explosiver Zug, Übergang und Straight-Bar-Dip.',gate:'8 hohe Pull-ups + 10 Straight-Bar-Dips sauber',drills:[{name:'Chest-to-Bar Pull-up',dose:'4 × 6–8',cue:'Brust aktiv zur Stange ziehen.',error:'Nur Kinn über Stange.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Chest-to-Bar Pull-up calisthenics tutorial')},{name:'Explosive High Pull',dose:'5 × 3–5',cue:'Schnell und hoch Richtung untere Brust ziehen.',error:'Kipping statt Zugkraft.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Explosive High Pull calisthenics tutorial')},{name:'Straight-Bar Dip',dose:'4 × 8–12',cue:'Oben stabil, kontrolliert tief drücken.',error:'Schultern nach vorn kollabieren.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Straight-Bar Dip calisthenics tutorial')}]},
'Front Lever':{source:'https://www.youtube.com/results?search_query=front+lever+progression+calisthenics+tutorial',visual:skills.find(x=>x.name==='Front Lever')?.icon||'🎯',intro:'Straight-arm Zugkraft, Schulterblattkontrolle und Hollow-Spannung.',gate:'4 × 10 s Tuck Front Lever',drills:[{name:'Active Hang',dose:'3 × 20 s',cue:'Schulterblätter aktiv nach unten ziehen.',error:'Passiv in Schultern hängen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Active Hang calisthenics tutorial')},{name:'Tuck Front Lever',dose:'4 × 10 s',cue:'Hüfte hoch, Rücken möglichst parallel.',error:'Hüfte absinken lassen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Tuck Front Lever calisthenics tutorial')},{name:'Tuck Lever Rows',dose:'3 × 6',cue:'Körperposition halten und kontrolliert ziehen.',error:'Position bei jeder Wiederholung verlieren.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Tuck Lever Rows calisthenics tutorial')}]},
'Back Lever':{source:'https://www.youtube.com/results?search_query=back+lever+progression+calisthenics+tutorial',visual:skills.find(x=>x.name==='Back Lever')?.icon||'🎯',intro:'Schulterextension, Straight-arm-Kraft und Körperspannung.',gate:'4 × 10 s Tuck Back Lever',drills:[{name:'German Hang',dose:'3 × 20 s',cue:'Nur schmerzfreie Schulterposition.',error:'In Schulterdehnung hineinzwingen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('German Hang calisthenics tutorial')},{name:'Skin the Cat',dose:'3 × 5',cue:'Langsam und kontrolliert rotieren.',error:'Schwung benutzen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Skin the Cat calisthenics tutorial')},{name:'Tuck Back Lever',dose:'4 × 10 s',cue:'Arme gestreckt, Hüfte stabil.',error:'Ellbogen beugen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Tuck Back Lever calisthenics tutorial')}]},
'Planche':{source:'https://www.youtube.com/results?search_query=planche+progression+beginner+calisthenics+tutorial',visual:skills.find(x=>x.name==='Planche')?.icon||'🎯',intro:'Handgelenke, Protraktion und Straight-arm-Druckkraft.',gate:'4 × 20 s starker Planche Lean',drills:[{name:'Planche Lean',dose:'4 × 20 s',cue:'Schultern vor Hände, Schulterblätter aktiv auseinander.',error:'Ellbogen beugen; Hüfte hängen lassen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Planche Lean calisthenics tutorial')},{name:'Frog Stand',dose:'4 × 20 s',cue:'Gewicht langsam nach vorn verlagern.',error:'Nach vorn springen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Frog Stand calisthenics tutorial')},{name:'Pseudo Planche Push-up',dose:'3 × 8',cue:'Vorlage während der Wiederholung halten.',error:'Zur normalen Push-up-Position zurückweichen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Pseudo Planche Push-up calisthenics tutorial')}]},
'Human Flag':{source:'https://www.youtube.com/results?search_query=human+flag+progression+calisthenics+tutorial',visual:skills.find(x=>x.name==='Human Flag')?.icon||'🎯',intro:'Seitliche Core-Kraft, Schulterstabilität und Push-Pull-Koordination.',gate:'4 × 10 s Tuck Flag',drills:[{name:'Side Plank',dose:'3 × 45 s je Seite',cue:'Körper in einer Linie halten.',error:'Hüfte absinken lassen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Side Plank calisthenics tutorial')},{name:'Vertical Flag Hold',dose:'4 × 15 s',cue:'Oberer Arm zieht, unterer drückt.',error:'Beide Arme nur ziehen lassen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Vertical Flag Hold calisthenics tutorial')},{name:'Tuck Flag',dose:'4 × 10 s',cue:'Knie kompakt, Hüfte hoch.',error:'Schulterposition verlieren.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Tuck Flag calisthenics tutorial')}]},
'Dragon Flag':{source:'https://www.youtube.com/results?search_query=dragon+flag+progression+tutorial',visual:skills.find(x=>x.name==='Dragon Flag')?.icon||'🎯',intro:'Anti-Extension-Core und kontrollierte Ganzkörperspannung.',gate:'3 × 5 kontrollierte Negative',drills:[{name:'Hollow Body Hold',dose:'3 × 30 s',cue:'Lendenwirbelsäule am Boden.',error:'Hohlkreuz.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Hollow Body Hold calisthenics tutorial')},{name:'Hanging Leg Raise',dose:'3 × 10',cue:'Becken aktiv einrollen.',error:'Nur aus Hüfte schwingen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Hanging Leg Raise calisthenics tutorial')},{name:'Dragon Flag Negative',dose:'3 × 5',cue:'Körper als Einheit langsam ablassen.',error:'In Hüfte einknicken.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Dragon Flag Negative calisthenics tutorial')}]},
'One-Arm Pull-up':{source:'https://www.youtube.com/results?search_query=one+arm+pull+up+progression+FitnessFAQs',visual:skills.find(x=>x.name==='One-Arm Pull-up')?.icon||'🎯',intro:'Sehr hohe einarmige Zugkraft und Schulterblattkontrolle.',gate:'3 × 5 Archer Pull-ups je Seite',drills:[{name:'Archer Pull-up',dose:'3 × 5 je Seite',cue:'Zur Arbeitsseite ziehen, Gegenarm lang.',error:'Körper stark verdrehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Archer Pull-up calisthenics tutorial')},{name:'Assisted One-Arm Pull-up',dose:'4 × 4 je Seite',cue:'Hilfshand nur minimal einsetzen.',error:'Mit Hilfshand Hauptarbeit leisten.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Assisted One-Arm Pull-up calisthenics tutorial')},{name:'One-Arm Negative',dose:'4 × 3 je Seite',cue:'5 Sekunden kontrolliert ablassen.',error:'Unkontrolliert fallen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('One-Arm Negative calisthenics tutorial')}]},
'V-Sit':{source:'https://www.youtube.com/results?search_query=V-sit+progression+calisthenics+tutorial',visual:skills.find(x=>x.name==='V-Sit')?.icon||'🎯',intro:'L-Sit-Basis plus deutlich stärkere aktive Kompression.',gate:'3 × 20 s L-Sit + 3 × 10 Compression Lifts',drills:[{name:'L-Sit',dose:'3 × 20 s',cue:'Knie gestreckt, Schultern tief.',error:'Rund werden und einsinken.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('L-Sit calisthenics tutorial')},{name:'Pike Compression Lift',dose:'3 × 10',cue:'Beine aktiv vom Boden heben.',error:'Nach hinten lehnen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Pike Compression Lift calisthenics tutorial')},{name:'High L-Sit',dose:'4 × 10 s',cue:'Hüfte aktiv nach vorn/oben drücken.',error:'Nur Füße hochziehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('High L-Sit calisthenics tutorial')}]},
'Press to Handstand':{source:'https://www.youtube.com/results?search_query=press+to+handstand+progression+tutorial',visual:skills.find(x=>x.name==='Press to Handstand')?.icon||'🎯',intro:'Kompression, Schultervorlage und kontrollierter Gewichtstransfer.',gate:'3 × 5 Box Press Drills sauber',drills:[{name:'Pike Compression',dose:'3 × 10',cue:'Beine aktiv anheben.',error:'Nur Oberkörper beugen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Pike Compression calisthenics tutorial')},{name:'Box Press Drill',dose:'4 × 5',cue:'Hüfte über Schultern bringen.',error:'Abspringen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Box Press Drill calisthenics tutorial')},{name:'Negative Press',dose:'4 × 3',cue:'Aus Handstand langsam kontrolliert absenken.',error:'Fallen lassen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Negative Press calisthenics tutorial')}]},
'90° Hold':{source:'https://www.youtube.com/results?search_query=90+degree+hold+calisthenics+progression',visual:skills.find(x=>x.name==='90° Hold')?.icon||'🎯',intro:'Bent-arm-Kraft, Planche-Vorlage und Core-Spannung.',gate:'4 × 5 s Assisted 90° Hold',drills:[{name:'Pseudo Planche Push-up',dose:'3 × 8',cue:'Vorlage halten.',error:'Schultern hinter Hände.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Pseudo Planche Push-up calisthenics tutorial')},{name:'Bent-Arm Stand',dose:'4 × 10 s',cue:'Ellbogen stabil, Körper kompakt.',error:'Auf Gelenke kollabieren.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Bent-Arm Stand calisthenics tutorial')},{name:'Negative 90°',dose:'4 × 3',cue:'Langsam in 90°-Position absenken.',error:'Zu schnell ablassen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Negative 90° calisthenics tutorial')}]},
'Shrimp Squat':{source:'https://www.youtube.com/results?search_query=shrimp+squat+progression+tutorial',visual:skills.find(x=>x.name==='Shrimp Squat')?.icon||'🎯',intro:'Einbeinige Kniekraft und Balance mit anderer Hebelposition als Pistol.',gate:'3 × 8 Assisted Shrimp je Seite',drills:[{name:'Reverse Lunge',dose:'3 × 10 je Seite',cue:'Kontrolliert senken.',error:'Vorderes Knie nach innen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Reverse Lunge calisthenics tutorial')},{name:'Assisted Shrimp',dose:'3 × 8 je Seite',cue:'Leicht festhalten, hinteres Knie Richtung Boden.',error:'Am Halt hochziehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Assisted Shrimp calisthenics tutorial')},{name:'Partial Shrimp',dose:'3 × 6 je Seite',cue:'Tiefe schrittweise erhöhen.',error:'In untere Position fallen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Partial Shrimp calisthenics tutorial')}]},
'Dragon Squat':{source:'https://www.youtube.com/results?search_query=dragon+squat+progression+calisthenics',visual:skills.find(x=>x.name==='Dragon Squat')?.icon||'🎯',intro:'Tiefe einbeinige Kraft, Hüftmobilität und Rotation.',gate:'3 × 6 Assisted Dragon je Seite',drills:[{name:'Cossack Squat',dose:'3 × 8 je Seite',cue:'Hüfte tief, Arbeitsfuß voll belasten.',error:'Ferse abheben.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Cossack Squat calisthenics tutorial')},{name:'Curtsy Lunge',dose:'3 × 8 je Seite',cue:'Kontrollierte Kreuzbewegung.',error:'Knie verdrehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Curtsy Lunge calisthenics tutorial')},{name:'Assisted Dragon Squat',dose:'3 × 6 je Seite',cue:'Unterstützung für Balance nutzen.',error:'Mit den Armen hochziehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Assisted Dragon Squat calisthenics tutorial')}]},
'Handstand Walk':{source:'https://www.youtube.com/results?search_query=handstand+walk+progression+tutorial',visual:skills.find(x=>x.name==='Handstand Walk')?.icon||'🎯',intro:'Freier Handstand plus kontrollierte Gewichtsverlagerung von Hand zu Hand.',gate:'10 saubere Shoulder Taps + 20 s freier Handstand',drills:[{name:'Wall Shoulder Taps',dose:'3 × 10',cue:'Gewicht vollständig auf eine Hand verlagern.',error:'Hüfte stark verdrehen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Wall Shoulder Taps calisthenics tutorial')},{name:'Freie Weight Shifts',dose:'4 × 20 s',cue:'Kleine kontrollierte Verlagerungen.',error:'Große hektische Schritte.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Freie Weight Shifts calisthenics tutorial')},{name:'2–5 Handstand-Schritte',dose:'8 Versuche',cue:'Kleine Schritte, Schulter aktiv.',error:'Nach vorn rennen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('2–5 Handstand-Schritte calisthenics tutorial')}]},
'One-Arm Handstand':{source:'https://www.youtube.com/results?search_query=one+arm+handstand+progression+tutorial',visual:skills.find(x=>x.name==='One-Arm Handstand')?.icon||'🎯',intro:'Sehr fortgeschrittene Balance; erst mit stabilem freien Handstand sinnvoll.',gate:'45 s freier Handstand + kontrollierte Weight Shifts',drills:[{name:'Handstand Weight Shifts',dose:'4 × 20 s',cue:'Schulter über tragende Hand bringen.',error:'Nur Hüfte verschieben.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Handstand Weight Shifts calisthenics tutorial')},{name:'Finger-Assisted One Arm',dose:'5 × 10 s je Seite',cue:'Hilfshand schrittweise entlasten.',error:'Hilfshand voll belasten.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('Finger-Assisted One Arm calisthenics tutorial')},{name:'One-Hand Wall Hold',dose:'4 × 10 s je Seite',cue:'Linie stabil halten.',error:'In Schulter einsinken.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent('One-Hand Wall Hold calisthenics tutorial')}]},
};
function planForSkill(skill){return skillPlans[skill.name]||{source:'https://www.youtube.com/results?search_query='+encodeURIComponent(skill.name+' calisthenics progression tutorial'),visual:skill.icon,intro:'Schrittweise Progression mit sauberer Technik.',gate:'Aktuelle Stufe sauber und reproduzierbar',drills:skill.steps.slice(0,3).map(x=>({name:x,dose:'3–4 saubere Sätze',cue:'Kontrolliert und ohne Schwung.',error:'Technikverlust oder Schmerzen.',video:'https://www.youtube.com/results?search_query='+encodeURIComponent(x+' calisthenics tutorial')}))}}

const dailyPlans = [
  {name:'Ganzkörper A',focus:'Zug · Beine · Druck · Rücken · Schulter · Core · Arme',blocks:[['e3','e18'],['e5','e4'],['e11','e8'],['e25','e31']]},
  {name:'Ganzkörper B',focus:'Hintere Kette · Brust · Rücken · Gesäß · Schulter · Core · Unterarme',blocks:[['e17','e7'],['e0','e21'],['e12','e10'],['e27','e29']]},
  {name:'Ganzkörper C',focus:'Beine · obere Brust · Rücken · Gesäß · Schulter · Core · Arme',blocks:[['e18','e6'],['e4','e23'],['e13','e9'],['e24','e31']]}
];
const defaults={xp:280,level:3,streak:0,exercises:baseExercises,skillProgress:{},equipment:{pullup:true,bench:true,dumbbell:true,bands:true,rack:false,barbell:false,rings:false,dips:false},quests:{date:'',train:false,skill:false,challenge:false},records:{spiderman:0},workouts:0,bodyChecks:[],settings:{gameMode:true,coachTone:'motivierend',reminders:false},planRotation:0,lastDailyCompletedDate:'',customSelection:[],activeWorkout:null,skillGoals:{},skillSessions:{},skillEvidence:{},bossWins:{}};
function localDateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function load(){
  try{
    const raw=JSON.parse(localStorage.getItem('fitquest-state')||'{}');
    const s={...structuredClone(defaults),...raw};
    s.settings={...defaults.settings,...raw.settings};
    s.equipment={...defaults.equipment,...raw.equipment};
    s.records={...defaults.records,...raw.records};
    s.skillGoals={...defaults.skillGoals,...raw.skillGoals};
    s.skillSessions={...defaults.skillSessions,...raw.skillSessions};
    s.skillEvidence={...defaults.skillEvidence,...raw.skillEvidence}; s.bossWins={...defaults.bossWins,...raw.bossWins};
    s.quests={...defaults.quests,...raw.quests};
    if(!Array.isArray(s.exercises)||!s.exercises.length)s.exercises=structuredClone(baseExercises);
    if(!Array.isArray(s.customSelection))s.customSelection=[];
    return s;
  }catch{return structuredClone(defaults)}
}
let state=load();
function save(){localStorage.setItem('fitquest-state',JSON.stringify(state))}
function ensureDailyReset(render=false){
  const today=localDateKey();
  if(state.quests.date!==today){
    state.quests={date:today,train:false,skill:false,challenge:false};
    if(state.activeWorkout && state.activeWorkout.date!==today)state.activeWorkout=null;
    save();
    if(render && currentView==='home')home();
  }
}
function scheduleMidnightReset(){
  const now=new Date();
  const next=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1,0,0,0,150);
  setTimeout(()=>{ensureDailyReset(true);scheduleMidnightReset()},next-now);
}
const $=s=>document.querySelector(s); const view=$('#view');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2400)}
function levelFromXp(){state.level=Math.floor(state.xp/500)+1;return state.level}
function addXp(n,msg){state.xp+=n;levelFromXp();save();toast(`${msg||'Stark!'} +${n} XP ⚡`)}
function header(){document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));}
let currentView='home';
const pct=(v,max)=>Math.min(100,Math.round(v/max*100));
function completeQuest(k,xp,msg){ensureDailyReset();if(state.quests[k])return false;state.quests[k]=true;save();addXp(xp,msg||'Daily Quest geschafft!');return true}
function home(){
  ensureDailyReset();levelFromXp();const next=500-(state.xp%500), plan=currentDailyPlan();
  view.innerHTML=`
<section class="hero"><div class="levelrow"><div><div class="muted">DEIN CHARAKTER</div><div class="level">LEVEL ${state.level}</div></div><div class="xp">⚡ ${state.xp} XP</div></div><div class="bar"><i style="width:${pct(state.xp%500,500)}%"></i></div><div class="statrow"><div class="stat"><b>${state.workouts}</b><span class="tiny">Workouts</span></div><div class="stat"><b>${Object.values(state.skillProgress).filter(x=>x>=5).length}</b><span class="tiny">Skills</span></div><div class="stat"><b>${state.records.spiderman}</b><span class="tiny">Spider-Runden</span></div><div class="stat"><b>${next}</b><span class="tiny">XP bis Level</span></div></div></section>
<div class="sectiontitle"><h2>🎯 Heute</h2><span class="tag green">${plan.name}</span></div>
<div class="card"><h3>Coach sagt</h3><p class="muted">Heute stehen ${plan.blocks.flat().length} Übungen in vier Wechselblöcken an. Unterschiedliche Muskelgruppen wechseln sich ab, damit du die Einheit kompakt halten kannst. Schwere Sätze bekommen trotzdem die Pause, die du brauchst.</p><button class="btn block" onclick="go('training')">Daily Training öffnen</button></div>
<div class="sectiontitle"><h2>📜 Daily Quests</h2><span class="muted">Reset täglich 00:00</span></div>
<div class="card">${quest('train','Training absolvieren',250)}${quest('skill','10 Min. Skilltraining',120)}${quest('challenge','Spider-Man-Challenge',300)}</div>
<div class="sectiontitle"><h2>👹 Nächster Boss</h2></div>
<div class="boss"><div class="bossicon">🦵</div><div class="muted">BOSSFIGHT</div><h2>Der Einbeinige</h2><p>Pistol Squat – finde zuerst dein aktuelles Level.</p><button class="btn warn" onclick="openSkill('s0')">Skill prüfen</button></div>`
}
function quest(k,label,xp){return `<div class="quest" onclick="toggleQuest('${k}',${xp})"><div class="check ${state.quests[k]?'done':''}">${state.quests[k]?'✓':''}</div><div><b>${label}</b><div class="muted">${state.quests[k]?'Heute erledigt':`+${xp} XP`}</div></div></div>`}
window.toggleQuest=(k,xp)=>{ensureDailyReset();if(state.quests[k])return toast('Heute schon erledigt ✅');completeQuest(k,xp,'Quest geschafft!');home()}
function currentDailyPlan(){return dailyPlans[(state.planRotation||0)%dailyPlans.length]}
function getExercise(id){return state.exercises.find(e=>e.id===id)}
function sessionDone(id){return !!(state.activeWorkout&&state.activeWorkout.date===localDateKey()&&state.activeWorkout.done&&state.activeWorkout.done[id])}
function startSession(mode,ids,title){
  const cur=state.activeWorkout;
  if(!cur||cur.date!==localDateKey()||cur.mode!==mode||JSON.stringify(cur.ids)!==JSON.stringify(ids)){
    state.activeWorkout={date:localDateKey(),mode,title,ids:[...ids],done:{}};save();
  }
}
function training(){showDailyTraining()}
function trainingTabs(active){return `<div class="tabs"><button class="tab ${active==='daily'?'active':''}" onclick="showDailyTraining()">Heute</button><button class="tab ${active==='custom'?'active':''}" onclick="showCustomBuilder()">Individuell</button><button class="tab ${active==='catalog'?'active':''}" onclick="showAllExercises()">Übungen</button><button class="tab ${active==='challenge'?'active':''}" onclick="challenge()">🕷️ Challenge</button></div>`}
function showDailyTraining(){
  const plan=currentDailyPlan(), ids=plan.blocks.flat();startSession('daily',ids,plan.name);
  const done=ids.filter(sessionDone).length;
  view.innerHTML=`<div class="sectiontitle"><div><h2>🏋️ Daily Training</h2><div class="muted">${plan.name} · ca. 30–45 Min.</div></div><span class="tag green">${done}/${ids.length}</span></div>
  ${trainingTabs('daily')}
  <div class="training-summary"><b>Heute auf einen Blick</b><span>${plan.focus}</span><small>Vier Wechselblöcke: A → B → A → B. So bekommt die gerade belastete Muskelgruppe während der anderen Übung Zeit zur Erholung.</small></div>
  <div class="workout-overview">${plan.blocks.map((b,i)=>workoutBlock(b,i)).join('')}</div>
  <button class="btn block" style="margin-top:14px" onclick="completeWorkout('daily')">✅ Training abschließen</button>`
}
window.showDailyTraining=showDailyTraining;
function workoutBlock(ids,i){
  const letters=['A','B','C','D'];
  return `<section class="pairblock"><div class="pairhead"><b>Wechselblock ${letters[i]}</b><span>abwechselnd</span></div>${ids.map((id,n)=>compactExercise(getExercise(id),n+1)).join('')}</section>`
}
function compactExercise(e,n){if(!e)return '';const done=sessionDone(e.id);return `<div class="compact-exercise ${done?'isdone':''}"><div class="exno">${done?'✓':n}</div><button class="exercise-main" onclick="logExercise('${e.id}')"><b>${e.name}</b><span>${e.group} · ${e.equipment}</span></button><div class="exercise-target"><b>${e.target||'3 × 8–12'}</b><span>${e.load||'Gewicht offen'}</span></div></div>`}
function groupExercises(exercises,renderRow){
  const groups={};exercises.forEach(e=>(groups[e.group||'Sonstiges']??=[]).push(e));
  return Object.entries(groups).sort((a,b)=>a[0].localeCompare(b[0],'de')).map(([g,es])=>`<details class="exgroup"><summary>${g}<span>${es.length}</span></summary><div class="list">${es.map(renderRow).join('')}</div></details>`).join('')
}
window.showAllExercises=()=>{view.innerHTML=`<div class="sectiontitle"><h2>Übungskatalog</h2><button class="btn" onclick="openExerciseForm()">+ Neue Übung</button></div>${trainingTabs('catalog')}<div class="notice">Dein kompletter Katalog bleibt editierbar. Muskelgruppen sind eingeklappt, damit du schneller findest, was du suchst.</div><div style="margin-top:12px">${groupExercises(state.exercises.filter(e=>e.active),e=>exerciseRow(e))}</div>`}
function exerciseRow(e){return `<div class="exercise"><div><div class="name">${e.name}</div><div class="muted">${e.equipment} · Ziel ${e.target}</div></div><button class="btn secondary small" onclick="logExercise('${e.id}')">Eintragen</button></div>`}
window.showCustomBuilder=()=>{
  const selected=new Set(state.customSelection||[]);
  view.innerHTML=`<div class="sectiontitle"><div><h2>🎛️ Individuelles Training</h2><div class="muted">Bis zu 8 Übungen frei wählen</div></div><span class="tag ${selected.size===8?'yellow':'green'}">${selected.size}/8</span></div>${trainingTabs('custom')}
  <div class="training-summary"><b>Deine Session</b><span>${selected.size?`${selected.size} Übungen gewählt`:'Noch nichts gewählt'}</span><small>Wähle frei aus deinem Katalog. Die Reihenfolge kannst du anschließend automatisch muskelgruppenfreundlich sortieren lassen.</small></div>
  <div class="custom-actions"><button class="btn secondary" onclick="autoOrderCustom()">↕️ Sinnvoll sortieren</button><button class="btn ${selected.size?'':'disabled'}" onclick="startCustomWorkout()">▶ Starten</button></div>
  <div style="margin-top:12px">${groupExercises(state.exercises.filter(e=>e.active),e=>customPickRow(e,selected.has(e.id)))}</div>`
}
function customPickRow(e,checked){return `<label class="exercise pickrow"><div><div class="name">${e.name}</div><div class="muted">${e.equipment} · ${e.target}</div></div><input type="checkbox" ${checked?'checked':''} onchange="toggleCustom('${e.id}',this.checked)"></label>`}
window.toggleCustom=(id,on)=>{state.customSelection=state.customSelection||[];if(on&&!state.customSelection.includes(id)){if(state.customSelection.length>=8){toast('Maximal 8 Übungen');showCustomBuilder();return}state.customSelection.push(id)}if(!on)state.customSelection=state.customSelection.filter(x=>x!==id);save();showCustomBuilder()}
function muscleBucket(group=''){const g=group.toLowerCase();if(g.includes('rücken')||g.includes('bizeps'))return 'pull';if(g.includes('brust')||g.includes('trizeps')||g.includes('schulter'))return 'push';if(g.includes('bein')||g.includes('waden')||g.includes('oberschenkel')||g.includes('po'))return 'legs';if(g.includes('bauch')||g.includes('core'))return 'core';if(g.includes('unterarm'))return 'forearm';return 'other'}
window.autoOrderCustom=()=>{
  const src=(state.customSelection||[]).map(getExercise).filter(Boolean), buckets={};src.forEach(e=>(buckets[muscleBucket(e.group)]??=[]).push(e.id));
  const order=['pull','legs','push','core','forearm','other'];const out=[];let changed=true;
  while(changed){changed=false;for(const k of order){if(buckets[k]?.length){out.push(buckets[k].shift());changed=true}}}
  state.customSelection=out;save();toast('Muskelgruppen abwechselnd sortiert ↕️');showCustomBuilder();
}
window.startCustomWorkout=()=>{const ids=(state.customSelection||[]).slice(0,8);if(!ids.length)return toast('Wähle mindestens eine Übung');startSession('custom',ids,'Individuelles Training');renderCustomWorkout()}
function renderCustomWorkout(){const ids=state.activeWorkout?.mode==='custom'?state.activeWorkout.ids:(state.customSelection||[]);view.innerHTML=`<div class="sectiontitle"><div><h2>🎛️ Individuelles Training</h2><div class="muted">${ids.length} Übungen</div></div><span class="tag green">${ids.filter(sessionDone).length}/${ids.length}</span></div>${trainingTabs('custom')}<div class="workout-overview single">${ids.map((id,i)=>compactExercise(getExercise(id),i+1)).join('')}</div><button class="btn block" style="margin-top:14px" onclick="completeWorkout('custom')">✅ Training abschließen</button><button class="btn secondary block" style="margin-top:8px" onclick="showCustomBuilder()">Übungen ändern</button>`}
window.openExerciseForm=()=>modal(`<h2>Neue Übung</h2><div class="formgrid">
<div class="field"><label>Name</label><input id="fName" placeholder="z. B. einarmiges Rudern"></div>
<div class="field"><label>Muskelgruppe</label><input id="fGroup" placeholder="z. B. Rücken"></div>
<div class="field"><label>Equipment</label><select id="fEq"><option>Körpergewicht</option><option>Kurzhantel</option><option>Kurzhantel + Bank</option><option>Band</option><option>Klimmzugstange</option><option>Sonstiges</option></select></div>
<div class="field"><label>Gewicht / Band</label><input id="fLoad" placeholder="z. B. 17,5 kg oder lila"></div>
<div class="field"><label>Ziel</label><input id="fTarget" value="3 × 8–12"></div>
<button class="btn" onclick="saveExercise()">Übung speichern</button></div>`)
window.saveExercise=()=>{const name=$('#fName').value.trim();if(!name)return toast('Bitte Namen eingeben');state.exercises.push({id:'u'+Date.now(),name,group:$('#fGroup').value||'Sonstiges',equipment:$('#fEq').value,load:$('#fLoad').value,target:$('#fTarget').value||'3 × 8–12',active:true,history:[]});save();closeModal();toast('Übung hinzugefügt ✅');showAllExercises()}
window.logExercise=id=>{const e=getExercise(id);if(!e)return;modal(`<h2>${e.name}</h2><div class="formgrid"><div class="field"><label>Gewicht / Band</label><input id="lLoad" value="${e.load||''}"></div><div class="field"><label>Geschaffte Wiederholungen / Sekunden</label><input id="lReps" placeholder="z. B. 12, 11, 10"></div><div class="field"><label>Wie schwer?</label><select id="lRpe"><option>leicht</option><option selected>passend</option><option>schwer</option><option>sehr schwer</option></select></div><button class="btn" onclick="saveLog('${id}')">✅ Leistung speichern & abhaken</button></div>`)}
window.saveLog=id=>{const e=getExercise(id);e.load=$('#lLoad').value;e.history=e.history||[];e.history.push({date:new Date().toISOString(),reps:$('#lReps').value,load:e.load,rpe:$('#lRpe').value});if(state.activeWorkout&&state.activeWorkout.date===localDateKey()&&state.activeWorkout.ids.includes(id))state.activeWorkout.done[id]=true;save();closeModal();addXp(15,'Leistung gespeichert!');if(currentView==='training'){state.activeWorkout?.mode==='custom'?renderCustomWorkout():showDailyTraining()}}
window.completeWorkout=(mode='daily')=>{const ids=state.activeWorkout?.ids||[];const done=ids.filter(sessionDone).length;if(ids.length&&done<Math.ceil(ids.length/2)&&!confirm(`Erst ${done}/${ids.length} Übungen abgehakt. Training trotzdem abschließen?`))return;state.workouts++;if(mode==='daily'){state.planRotation=((state.planRotation||0)+1)%dailyPlans.length;state.lastDailyCompletedDate=localDateKey()}state.activeWorkout=null;save();const gotQuest=completeQuest('train',250,'Daily Training geschafft!');if(!gotQuest){addXp(50,'Workout abgeschlossen!')}home()}
function skillsView(filter='Alle'){const fams=['Alle',...new Set(skills.map(s=>s.family))];view.innerHTML=`<div class="sectiontitle"><h2>🗺️ Skill-Welt</h2><span class="tag yellow">RPG-Modus</span></div><div class="tabs">${fams.map(f=>`<button class="tab ${f===filter?'active':''}" onclick="skillsView('${f}')">${f}</button>`).join('')}</div><div class="skillmap">${skills.filter(s=>filter==='Alle'||s.family===filter).map(skillCard).join('')}</div>`}
function skillCard(s){const p=state.skillProgress[s.id]??0,win=!!state.bossWins[s.id];return `<div class="skill ${win?'mastered':''}"><span class="badge">${win?'🏆':'⚔️'}</span><div class="muted">${s.family}</div><h3>${s.icon} ${s.name}</h3><div>${win?'Boss besiegt':`Stufe ${Math.min(p+1,s.steps.length)}/${s.steps.length}: ${s.steps[Math.min(p,s.steps.length-1)]}`}</div><div class="skillbar"><i style="width:${pct(p,s.steps.length)}%"></i></div><button class="btn secondary" style="margin-top:10px" onclick="openSkill('${s.id}')">${p?'Weitertrainieren':'Einstufen'}</button></div>`}
window.skillsView=skillsView;
window.openSkill=id=>{const s=skills.find(x=>x.id===id),p=state.skillProgress[id]??0,plan=planForSkill(s),goal=!!state.skillGoals[id],win=!!state.bossWins[id];if(win)return modal(`<div class="celebrate">🏆</div><h2>${s.name}</h2><p>Boss <b>${s.boss}</b> wurde besiegt.</p>`);if(p>=s.steps.length)return bossFight(id);modal(`<div class="skillhero"><div class="skillvisual">${plan.visual||s.icon}</div><div><div class="muted">${s.family} · Stufe ${p+1}/${s.steps.length}</div><h2>${s.name}</h2><p>${plan.intro}</p></div></div><a class="btn secondary block" href="${plan.source}" target="_blank" rel="noopener">▶ Skill ansehen</a><div class="card innercard"><div class="muted">AKTUELLE STUFE</div><h3>${s.steps[p]}</h3><p><b>Aufstiegskriterium:</b> ${plan.gate}</p><p class="muted">Kannst du die aktuelle Stufe sauber, kontrolliert und reproduzierbar?</p><div class="grid"><button class="btn danger" onclick="skillNo('${id}')">❌ Nein</button><button class="btn" onclick="skillGate('${id}')">✅ Ja – Leistung prüfen</button></div></div>${goal?`<button class="btn warn block" onclick="startSkillPlan('${id}')">🎯 Heute dafür trainieren</button>`:''}`)}
window.skillNo=id=>{state.skillGoals[id]=true;save();modal(`<div class="celebrate">🎯</div><h2>Ziel gesetzt</h2><p>Wir trainieren die nötigen Vorstufen. Erst ein sauber erfülltes Leistungskriterium schaltet die nächste Stufe frei.</p><button class="btn block" onclick="startSkillPlan('${id}')">🔥 Heute anfangen</button>`)}
window.skillGate=id=>{const s=skills.find(x=>x.id===id),plan=planForSkill(s);modal(`<div class="celebrate">🧪</div><h2>Level-Test: ${s.name}</h2><p>Erforderlich: <b>${plan.gate}</b></p><p class="muted">Nur bestätigen, wenn du das ohne Schmerz und mit sauberer Technik reproduzierbar geschafft hast.</p><button class="btn block" onclick="confirmSkillGate('${id}')">✅ Kriterium sauber erfüllt</button><button class="btn secondary block" style="margin-top:8px" onclick="startSkillPlan('${id}')">Noch trainieren</button>`)}
window.confirmSkillGate=id=>{const s=skills.find(x=>x.id===id);state.skillEvidence[id]=(state.skillEvidence[id]||0)+1;state.skillProgress[id]=Math.min((state.skillProgress[id]||0)+1,s.steps.length);save();closeModal();completeQuest('skill',120,'Skill-Quest geschafft!');addXp(75,'Skill-Stufe freigeschaltet!');if(state.skillProgress[id]>=s.steps.length)bossFight(id);else openSkill(id)}
window.startSkillPlan=id=>{const s=skills.find(x=>x.id===id),plan=planForSkill(s),count=state.skillSessions[id]||0;closeModal();view.innerHTML=`<div class="sectiontitle"><h2>${s.icon} ${s.name}</h2><span class="tag yellow">Skill-Training</span></div><div class="notice">Ziel: sauber trainieren, nicht erzwingen. Schmerz = abbrechen. Aufstieg erst nach bestandenem Leistungstest.</div><div class="card" style="margin-top:12px"><div class="muted">HEUTIGE VORBEREITUNG</div><h3>${s.name} · Einheit ${count+1}</h3><div class="list">${plan.drills.map((d,i)=>`<div class="exercise skilldrill"><label style="display:flex;gap:10px;align-items:flex-start;flex:1"><input type="checkbox" class="skillcheck"><div><div class="name">${i+1}. ${d.name}</div><div class="muted">${d.dose}</div><div class="tiny">💡 ${d.cue}</div><div class="tiny">⚠️ ${d.error}</div><a href="${d.video}" target="_blank" rel="noopener">▶ Video/Hilfe</a></div></label></div>`).join('')}</div><div class="notice"><b>Nächstes Level:</b> ${plan.gate}</div><button class="btn block" style="margin-top:12px" onclick="finishSkillSession('${id}')">✅ Training abschließen</button><button class="btn secondary block" style="margin-top:8px" onclick="skillGate('${id}')">🧪 Level-Test starten</button></div>`}
window.finishSkillSession=id=>{const boxes=[...document.querySelectorAll('.skillcheck')];if(boxes.some(x=>!x.checked)&&!confirm('Noch nicht alle Übungen abgehakt. Trotzdem abschließen?'))return;state.skillSessions[id]=(state.skillSessions[id]||0)+1;save();completeQuest('skill',120,'Skill-Quest geschafft!');addXp(40,'Skill-Training erledigt!');modal(`<div class="celebrate">🔥</div><h2>Geil gemacht!</h2><p>Einheit ${state.skillSessions[id]} abgeschlossen.</p><p class="muted">Kein automatischer Level-Up: Wenn du das Kriterium sicher erfüllst, starte den Level-Test.</p><button class="btn block" onclick="closeModal();openSkill('${id}')">Weiter</button>`)}
window.bossFight=id=>{const s=skills.find(x=>x.id===id),plan=planForSkill(s);modal(`<div class="celebrate">👹</div><h2>BOSSFIGHT: ${s.boss}</h2><p><b>${s.name}</b> – jetzt zählt der Zielskill selbst.</p><p class="muted">Vorbereitung abgeschlossen. Führe den vollständigen Skill sauber und kontrolliert aus. Bei Skills mit Halt: stabil halten; bei Wiederholungen: vollständiger Bewegungsumfang.</p><a class="btn secondary block" href="${plan.source}" target="_blank" rel="noopener">▶ Technik vorher ansehen</a><button class="btn block" style="margin-top:8px" onclick="winBoss('${id}')">⚔️ Boss sauber besiegt</button><button class="btn secondary block" style="margin-top:8px" onclick="startSkillPlan('${id}')">Noch nicht – weitertrainieren</button>`)}
window.winBoss=id=>{const s=skills.find(x=>x.id===id);state.bossWins[id]=new Date().toISOString();save();closeModal();addXp(750,`BOSS BESIEGT: ${s.boss}!`);modal(`<div class="celebrate">🏆</div><h2>${s.name} GEMEISTERT!</h2><p>🔥 Geil gemacht. <b>${s.boss}</b> ist besiegt.</p><p>+750 XP · Trophäe freigeschaltet</p><button class="btn block" onclick="closeModal();skillsView()">Zur Skill-Welt</button>`)}

function body(){view.innerHTML=`<div class="sectiontitle"><h2>📷 KI-Körpercheck</h2><span class="tag yellow">Beta</span></div><div class="notice">Diese lokale PWA kann Fotos bereits aufnehmen und speichern. Eine belastbare KI-Auswertung ist in dieser Version bewusst noch nicht aktiviert – dafür braucht die App ein Bildanalyse-Backend. Keine medizinischen Diagnosen.</div><div class="card" style="margin-top:12px"><h3>1. Entspannt</h3><div class="photozone"><input type="file" accept="image/*" capture="environment" onchange="previewPhoto(event,'relaxed')"><div class="muted">Vorne · hinten · seitlich, gleiches Licht und gleicher Abstand</div><div id="relaxedPreview"></div></div></div><div class="card" style="margin-top:12px"><h3>2. Angespannt</h3><div class="photozone"><input type="file" accept="image/*" capture="environment" onchange="previewPhoto(event,'flexed')"><div class="muted">Standardisierte Pose für Vergleichbarkeit</div><div id="flexedPreview"></div></div></div><div class="card" style="margin-top:12px"><h3>Geplante KI-Auswertung</h3><p class="muted">Symmetrie · sichtbare Proportionen · Körperhaltung · Links/Rechts-Vergleich · Verbindung mit unilateralem Leistungstest · passende Übungsvorschläge.</p><button class="btn secondary block" onclick="toast('KI-Modul bleibt für die nächste Backend-Stufe vorbereitet.')">Analyse starten</button></div>`}
window.previewPhoto=(ev,type)=>{const f=ev.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{document.getElementById(type+'Preview').innerHTML=`<img src="${r.result}" alt="Körperfoto">`;toast('Foto lokal geladen 📷')};r.readAsDataURL(f)}
function progress(){const mastered=skills.filter(s=>(state.skillProgress[s.id]??0)>=s.steps.length);view.innerHTML=`<div class="sectiontitle"><h2>🏆 Hall of Fame</h2><span class="tag green">Level ${state.level}</span></div><div class="hero"><div class="kpi">${state.xp} XP</div><div class="muted">Dein Fortschritt wird aus echten Aktionen aufgebaut.</div></div><div class="sectiontitle"><h2>Boss-Trophäen</h2></div>${mastered.length?mastered.map(s=>`<div class="exercise"><div><div class="name">🏆 ${s.boss}</div><div class="muted">${s.name} gemeistert</div></div><span>⚡ +750</span></div>`).join(''):'<div class="empty">Noch kein Boss besiegt. Dein erster wartet schon.</div>'}<div class="sectiontitle"><h2>Shadow You</h2></div><div class="boss"><div class="bossicon">🌑</div><h2>Dein früheres Ich</h2><p class="muted">Später erzeugt die App aus alten Bestleistungen einen persönlichen Bossfight. Aktueller Spider-Man-Rekord: ${state.records.spiderman} Runden.</p></div>`}
function settings(){modal(`<h2>⚙️ Einstellungen</h2><div class="formgrid"><div class="field"><label>Coach-Stil</label><select id="coachTone"><option ${state.settings.coachTone==='motivierend'?'selected':''}>motivierend</option><option>ruhig</option><option>knallhart</option></select></div><h3>Equipment</h3>${Object.entries({pullup:'Klimmzugstange',bench:'Kurzhantelbank',dumbbell:'Kurzhanteln',bands:'Reverse-/Widerstandsbänder',rack:'Rack',barbell:'Langhantel',rings:'Ringe',dips:'Dip-Barren'}).map(([k,n])=>`<label class="exercise"><span>${n}</span><input type="checkbox" id="eq_${k}" ${state.equipment[k]?'checked':''}></label>`).join('')}<div class="field"><label>Spielmodus</label><select id="gameMode"><option value="on" ${state.settings.gameMode?'selected':''}>An – XP, Quests, Bosse</option><option value="off" ${!state.settings.gameMode?'selected':''}>Aus – sachlich</option></select></div><button class="btn" onclick="saveSettings()">Speichern</button><button class="btn secondary" onclick="requestNotify()">🔔 Benachrichtigungen erlauben</button><button class="btn danger" onclick="resetApp()">App zurücksetzen</button></div>`)}
window.saveSettings=()=>{state.settings.coachTone=$('#coachTone').value;state.settings.gameMode=$('#gameMode').value==='on';for(const k of Object.keys(state.equipment))state.equipment[k]=$('#eq_'+k).checked;save();closeModal();toast('Einstellungen gespeichert ✅')}
window.requestNotify=async()=>{if(!('Notification'in window))return toast('Browser unterstützt das nicht');const p=await Notification.requestPermission();toast(p==='granted'?'Benachrichtigungen erlaubt 🔔':'Nicht erlaubt')}
window.resetApp=()=>{if(confirm('Wirklich alle lokalen App-Daten löschen?')){localStorage.removeItem('fitquest-state');state=structuredClone(defaults);ensureDailyReset();closeModal();home()}}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')};window.closeModal=closeModal;
function go(v){currentView=v;header();if(v==='home')home();if(v==='training')training();if(v==='skills')skillsView();if(v==='body')body();if(v==='progress')progress()};window.go=go;
document.querySelectorAll('.bottomnav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#closeModal').onclick=closeModal;$('#settingsBtn').onclick=settings;
$('#todayLabel').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(new Date());
ensureDailyReset();scheduleMidnightReset();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
go('home');
